# k8s/order-service/order-service-deployment.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: food-ordering-system
data:
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Database=OrderDb;Username=postgres;Password=postgres"
  ServiceUrls__UserService: "http://user-service:8080"
  ServiceUrls__RestaurantService: "http://restaurant-service:8081"
  JwtSettings__Issuer: "FoodOrderingSystem"
  JwtSettings__Audience: "FoodOrderingSystem"
  JwtSettings__ExpiryInHours: "24"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: food-ordering-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-services:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8082"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ConnectionStrings__DefaultConnection
        - name: ServiceUrls__UserService
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ServiceUrls__UserService
        - name: ServiceUrls__RestaurantService
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ServiceUrls__RestaurantService
        - name: JwtSettings__SecretKey
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: jwt-secret
        - name: JwtSettings__Issuer
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: JwtSettings__Issuer
        - name: JwtSettings__Audience
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: JwtSettings__Audience
        - name: JwtSettings__ExpiryInHours
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: JwtSettings__ExpiryInHours
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
       
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-ordering-system
spec:
  selector:
    app: order-service
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: food-ordering-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80